/*
 * This file is generated by jOOQ.
 */
package com.wuda.tester.mysql.orm.tables.records;


import com.wuda.tester.mysql.orm.tables.IndividualUserGeneral;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 个人用户－基本信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndividualUserGeneralRecord extends UpdatableRecordImpl<IndividualUserGeneralRecord> implements Record10<ULong, ULong, String, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = -2081395046;

    /**
     * Setter for <code>mysql_tester.individual_user_general.individual_user_general_id</code>.
     */
    public void setIndividualUserGeneralId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.individual_user_general_id</code>.
     */
    public ULong getIndividualUserGeneralId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.nickname</code>. 昵称
     */
    public void setNickname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.nickname</code>. 昵称
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.biography</code>. 个人简介。简短的介绍
     */
    public void setBiography(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.biography</code>. 个人简介。简短的介绍
     */
    public String getBiography() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.picture</code>. 用户图像。保存的是图片地址。命名来源：github
     */
    public void setPicture(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.picture</code>. 用户图像。保存的是图片地址。命名来源：github
     */
    public String getPicture() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>mysql_tester.individual_user_general.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>mysql_tester.individual_user_general.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, String, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<ULong, ULong, String, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.INDIVIDUAL_USER_GENERAL_ID;
    }

    @Override
    public Field<ULong> field2() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.NICKNAME;
    }

    @Override
    public Field<String> field4() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.BIOGRAPHY;
    }

    @Override
    public Field<String> field5() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.PICTURE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.CREATE_TIME;
    }

    @Override
    public Field<ULong> field7() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field9() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field10() {
        return IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getIndividualUserGeneralId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getNickname();
    }

    @Override
    public String component4() {
        return getBiography();
    }

    @Override
    public String component5() {
        return getPicture();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public ULong component7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component8() {
        return getLastModifyTime();
    }

    @Override
    public ULong component9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component10() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getIndividualUserGeneralId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getNickname();
    }

    @Override
    public String value4() {
        return getBiography();
    }

    @Override
    public String value5() {
        return getPicture();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public ULong value7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value8() {
        return getLastModifyTime();
    }

    @Override
    public ULong value9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value10() {
        return getIsDeleted();
    }

    @Override
    public IndividualUserGeneralRecord value1(ULong value) {
        setIndividualUserGeneralId(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value3(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value4(String value) {
        setBiography(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value5(String value) {
        setPicture(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value7(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value8(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value9(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord value10(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public IndividualUserGeneralRecord values(ULong value1, ULong value2, String value3, String value4, String value5, LocalDateTime value6, ULong value7, LocalDateTime value8, ULong value9, ULong value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualUserGeneralRecord
     */
    public IndividualUserGeneralRecord() {
        super(IndividualUserGeneral.INDIVIDUAL_USER_GENERAL);
    }

    /**
     * Create a detached, initialised IndividualUserGeneralRecord
     */
    public IndividualUserGeneralRecord(ULong individualUserGeneralId, ULong userId, String nickname, String biography, String picture, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(IndividualUserGeneral.INDIVIDUAL_USER_GENERAL);

        set(0, individualUserGeneralId);
        set(1, userId);
        set(2, nickname);
        set(3, biography);
        set(4, picture);
        set(5, createTime);
        set(6, createUserId);
        set(7, lastModifyTime);
        set(8, lastModifyUserId);
        set(9, isDeleted);
    }
}
