/*
 * This file is generated by jOOQ.
 */
package com.wuda.tester.mysql.orm.tables.records;


import com.wuda.tester.mysql.orm.tables.ItemGeneral;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 物品基本信息，也可以表示物品某个规格的基本信息，如果variation id不等于0
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemGeneralRecord extends UpdatableRecordImpl<ItemGeneralRecord> implements Record9<ULong, String, ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = 870942629;

    /**
     * Setter for <code>mysql_tester.item_general.item_general_id</code>.
     */
    public void setItemGeneralId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.item_general_id</code>.
     */
    public ULong getItemGeneralId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>mysql_tester.item_general.item_name</code>.
     */
    public void setItemName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.item_name</code>.
     */
    public String getItemName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mysql_tester.item_general.item_id</code>.
     */
    public void setItemId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.item_id</code>.
     */
    public ULong getItemId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>mysql_tester.item_general.item_variation_id</code>.
     */
    public void setItemVariationId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.item_variation_id</code>.
     */
    public ULong getItemVariationId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>mysql_tester.item_general.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>mysql_tester.item_general.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>mysql_tester.item_general.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>mysql_tester.item_general.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>mysql_tester.item_general.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>mysql_tester.item_general.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<ULong, String, ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<ULong, String, ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return ItemGeneral.ITEM_GENERAL.ITEM_GENERAL_ID;
    }

    @Override
    public Field<String> field2() {
        return ItemGeneral.ITEM_GENERAL.ITEM_NAME;
    }

    @Override
    public Field<ULong> field3() {
        return ItemGeneral.ITEM_GENERAL.ITEM_ID;
    }

    @Override
    public Field<ULong> field4() {
        return ItemGeneral.ITEM_GENERAL.ITEM_VARIATION_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ItemGeneral.ITEM_GENERAL.CREATE_TIME;
    }

    @Override
    public Field<ULong> field6() {
        return ItemGeneral.ITEM_GENERAL.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ItemGeneral.ITEM_GENERAL.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field8() {
        return ItemGeneral.ITEM_GENERAL.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field9() {
        return ItemGeneral.ITEM_GENERAL.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getItemGeneralId();
    }

    @Override
    public String component2() {
        return getItemName();
    }

    @Override
    public ULong component3() {
        return getItemId();
    }

    @Override
    public ULong component4() {
        return getItemVariationId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public ULong component6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component7() {
        return getLastModifyTime();
    }

    @Override
    public ULong component8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component9() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getItemGeneralId();
    }

    @Override
    public String value2() {
        return getItemName();
    }

    @Override
    public ULong value3() {
        return getItemId();
    }

    @Override
    public ULong value4() {
        return getItemVariationId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public ULong value6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value7() {
        return getLastModifyTime();
    }

    @Override
    public ULong value8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value9() {
        return getIsDeleted();
    }

    @Override
    public ItemGeneralRecord value1(ULong value) {
        setItemGeneralId(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value2(String value) {
        setItemName(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value3(ULong value) {
        setItemId(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value4(ULong value) {
        setItemVariationId(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value6(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value7(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value8(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public ItemGeneralRecord value9(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public ItemGeneralRecord values(ULong value1, String value2, ULong value3, ULong value4, LocalDateTime value5, ULong value6, LocalDateTime value7, ULong value8, ULong value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemGeneralRecord
     */
    public ItemGeneralRecord() {
        super(ItemGeneral.ITEM_GENERAL);
    }

    /**
     * Create a detached, initialised ItemGeneralRecord
     */
    public ItemGeneralRecord(ULong itemGeneralId, String itemName, ULong itemId, ULong itemVariationId, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(ItemGeneral.ITEM_GENERAL);

        set(0, itemGeneralId);
        set(1, itemName);
        set(2, itemId);
        set(3, itemVariationId);
        set(4, createTime);
        set(5, createUserId);
        set(6, lastModifyTime);
        set(7, lastModifyUserId);
        set(8, isDeleted);
    }
}
