/*
 * This file is generated by jOOQ.
 */
package com.wuda.tester.mysql.orm;


import com.wuda.tester.mysql.orm.tables.IndividualUserGeneral;
import com.wuda.tester.mysql.orm.tables.Item;
import com.wuda.tester.mysql.orm.tables.ItemDescription;
import com.wuda.tester.mysql.orm.tables.ItemGeneral;
import com.wuda.tester.mysql.orm.tables.Store;
import com.wuda.tester.mysql.orm.tables.StoreGeneral;
import com.wuda.tester.mysql.orm.tables.User;
import com.wuda.tester.mysql.orm.tables.records.IndividualUserGeneralRecord;
import com.wuda.tester.mysql.orm.tables.records.ItemDescriptionRecord;
import com.wuda.tester.mysql.orm.tables.records.ItemGeneralRecord;
import com.wuda.tester.mysql.orm.tables.records.ItemRecord;
import com.wuda.tester.mysql.orm.tables.records.StoreGeneralRecord;
import com.wuda.tester.mysql.orm.tables.records.StoreRecord;
import com.wuda.tester.mysql.orm.tables.records.UserRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>mysql_tester</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<IndividualUserGeneralRecord, ULong> IDENTITY_INDIVIDUAL_USER_GENERAL = Identities0.IDENTITY_INDIVIDUAL_USER_GENERAL;
    public static final Identity<ItemDescriptionRecord, ULong> IDENTITY_ITEM_DESCRIPTION = Identities0.IDENTITY_ITEM_DESCRIPTION;
    public static final Identity<ItemGeneralRecord, ULong> IDENTITY_ITEM_GENERAL = Identities0.IDENTITY_ITEM_GENERAL;
    public static final Identity<UserRecord, ULong> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IndividualUserGeneralRecord> KEY_INDIVIDUAL_USER_GENERAL_PRIMARY = UniqueKeys0.KEY_INDIVIDUAL_USER_GENERAL_PRIMARY;
    public static final UniqueKey<ItemRecord> KEY_ITEM_PRIMARY = UniqueKeys0.KEY_ITEM_PRIMARY;
    public static final UniqueKey<ItemDescriptionRecord> KEY_ITEM_DESCRIPTION_PRIMARY = UniqueKeys0.KEY_ITEM_DESCRIPTION_PRIMARY;
    public static final UniqueKey<ItemGeneralRecord> KEY_ITEM_GENERAL_PRIMARY = UniqueKeys0.KEY_ITEM_GENERAL_PRIMARY;
    public static final UniqueKey<StoreRecord> KEY_STORE_PRIMARY = UniqueKeys0.KEY_STORE_PRIMARY;
    public static final UniqueKey<StoreGeneralRecord> KEY_STORE_GENERAL_PRIMARY = UniqueKeys0.KEY_STORE_GENERAL_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<IndividualUserGeneralRecord, ULong> IDENTITY_INDIVIDUAL_USER_GENERAL = Internal.createIdentity(IndividualUserGeneral.INDIVIDUAL_USER_GENERAL, IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.INDIVIDUAL_USER_GENERAL_ID);
        public static Identity<ItemDescriptionRecord, ULong> IDENTITY_ITEM_DESCRIPTION = Internal.createIdentity(ItemDescription.ITEM_DESCRIPTION, ItemDescription.ITEM_DESCRIPTION.ITEM_DESCRIPTION_ID);
        public static Identity<ItemGeneralRecord, ULong> IDENTITY_ITEM_GENERAL = Internal.createIdentity(ItemGeneral.ITEM_GENERAL, ItemGeneral.ITEM_GENERAL.ITEM_GENERAL_ID);
        public static Identity<UserRecord, ULong> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.USER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<IndividualUserGeneralRecord> KEY_INDIVIDUAL_USER_GENERAL_PRIMARY = Internal.createUniqueKey(IndividualUserGeneral.INDIVIDUAL_USER_GENERAL, "KEY_individual_user_general_PRIMARY", new TableField[] { IndividualUserGeneral.INDIVIDUAL_USER_GENERAL.INDIVIDUAL_USER_GENERAL_ID }, true);
        public static final UniqueKey<ItemRecord> KEY_ITEM_PRIMARY = Internal.createUniqueKey(Item.ITEM, "KEY_item_PRIMARY", new TableField[] { Item.ITEM.ITEM_ID }, true);
        public static final UniqueKey<ItemDescriptionRecord> KEY_ITEM_DESCRIPTION_PRIMARY = Internal.createUniqueKey(ItemDescription.ITEM_DESCRIPTION, "KEY_item_description_PRIMARY", new TableField[] { ItemDescription.ITEM_DESCRIPTION.ITEM_DESCRIPTION_ID }, true);
        public static final UniqueKey<ItemGeneralRecord> KEY_ITEM_GENERAL_PRIMARY = Internal.createUniqueKey(ItemGeneral.ITEM_GENERAL, "KEY_item_general_PRIMARY", new TableField[] { ItemGeneral.ITEM_GENERAL.ITEM_GENERAL_ID }, true);
        public static final UniqueKey<StoreRecord> KEY_STORE_PRIMARY = Internal.createUniqueKey(Store.STORE, "KEY_store_PRIMARY", new TableField[] { Store.STORE.STORE_ID }, true);
        public static final UniqueKey<StoreGeneralRecord> KEY_STORE_GENERAL_PRIMARY = Internal.createUniqueKey(StoreGeneral.STORE_GENERAL, "KEY_store_general_PRIMARY", new TableField[] { StoreGeneral.STORE_GENERAL.STORE_GENERAL_ID }, true);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", new TableField[] { User.USER.USER_ID }, true);
    }
}
